// <auto-generated />
using System;
using BilgeKoleji.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BilgeKoleji.DAL.Migrations
{
    [DbContext(typeof(BilgeKolejiDbContext))]
    [Migration("20200804190711_deneme2")]
    partial class deneme2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BilgeKoleji.Model.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("BilgeKoleji.Model.GenelTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("GenelTablos");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DevamDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Ogretmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BransId")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BransId");

                    b.ToTable("Ogretmens");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sinifs");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Ders", b =>
                {
                    b.HasOne("BilgeKoleji.Model.Sinif", "Sinif")
                        .WithMany("Dersler")
                        .HasForeignKey("SinifId");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Ogrenci", b =>
                {
                    b.HasOne("BilgeKoleji.Model.Sinif", "Sube")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("SubeId");
                });

            modelBuilder.Entity("BilgeKoleji.Model.Ogretmen", b =>
                {
                    b.HasOne("BilgeKoleji.Model.Ders", "Brans")
                        .WithMany("Ogretmenler")
                        .HasForeignKey("BransId");
                });
#pragma warning restore 612, 618
        }
    }
}
