// <auto-generated />
namespace EgeBlogSite.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class saldım : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(saldım));
        
        string IMigrationMetadata.Id
        {
            get { return "202003092305335_saldım"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
